export { default as Contact } from './Contact';
export { default as Gallery } from './Gallery';
export { default as Hero } from './Hero';
export { default as Partners } from './Partners';
export { default as Story } from './Story';
export { default as Amenities } from './Amenities';
export { default as Description } from './Description';
export { default as Application } from './Application';
export { default as CallToAction } from './CallToAction';